name: .NET CI

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/Application/**'
  pull_request:
    paths:
      - 'src/Application/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet ../src/Application/src/RazorPagesTestSample/RazorPagesTestSample.csproj restore

    - name: Build
      run: dotnet build ../src/Application/src/RazorPagesTestSample/RazorPagesTestSample.csproj --no-restore

    - name: Test
      run: dotnet test ../src/Application/src/RazorPagesTestSample/RazorPagesTestSample.csproj --no-build --verbosity normal
